name: Build and Sign APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create Keystore & Sign APK
        run: |
          # ১. কি-স্টোর তৈরি
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          
          # ২. ZipAlign করা
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v -p 4 app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-aligned.apk
          
          # ৩. official apksigner দিয়ে সাইন করা
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks debug.keystore --ks-pass pass:android --key-pass pass:android --ks-key-alias androiddebugkey --out app/build/outputs/apk/debug/HishabKhata-Signed.apk app/build/outputs/apk/debug/app-aligned.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: HishabKhata-App
          path: app/build/outputs/apk/debug/HishabKhata-Signed.apk
